/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

plugins {
    id 'com.github.blindpirate.gogradle' version '0.11.4'
}

// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.windows.x86_64)
	//targetMachines = listOf(machines.windows.x86, machines.windows.x86_64, machines.macOS.x86_64, machines.linux.x86_64)
}

golang {
    packagePath = 'github.com/nater0000/golang-pkg' // import path of project, not file system path!
}

version = "0.0.1"
